#!/bin/bash

echo "Adding Flathub repository..."
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo --user

echo "Installing Steam..."
flatpak install flathub com.valvesoftware.Steam/x86_64/stable -y --user
flatpak install flathub runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable -y --user
flatpak install flathub net.lutris.Lutris/x86_64/stable -y --user
flatpak install flathub org.mozilla.firefox/x86_64/stable -y --user
flatpak install flathub org.polymc.PolyMC/x86_64/stable -y --user
#flatpak install flathub com.heroicgameslauncher.hgl/x86_64/stable -y --user
